spring:
  application:
    name: order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: root

  jpa:
    open-in-view: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
